openings = {
    # 1. e4 açilişlari    
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5'): "Italian Opening (Giuoco Piano)",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5'): "Ruy Lopez",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6'): "Ruy Lopez: Morphy Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nf6'): "Ruy Lopez: Berlin Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6'): "Two Knights Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5'): "Fried Liver Attack",
    ('e4', 'c5'): "Sicilian Defense",
    ('e4', 'c5', 'Nf3', 'd6'): "Sicilian: Dragon Variation Beginning",
    ('e4', 'c5', 'Nf3', 'Nc6'): "Sicilian: Closed Variation",
    ('e4', 'c5', 'Nf3', 'e6'): "Sicilian: Scheveningen Variation",
    ('e4', 'c5', 'Nf3', 'Nc6', 'Bb5'): "Sicilian: Rossolimo Variation",
    ('e4', 'c6'): "Caro-Kann Defense",
    ('e4', 'c6', 'd4', 'd5'): "Caro-Kann: Advance Variation",
    ('e4', 'e6'): "French Defense",
    ('e4', 'e6', 'd4', 'd5'): "French: Classical Variation",
    ('e4', 'e6', 'd4', 'd5', 'Nc3'): "French: Winawer Variation",
    ('e4', 'd6'): "Pirc Defense",
    ('e4', 'd6', 'd4', 'Nf6', 'Nc3'): "Pirc: Classical System",
    ('e4', 'Nf6'): "Alekhine Defense",
    ('e4', 'd5'): "Scandinavian Defense",
    ('e4', 'g6'): "Modern Defense",
    ('e4', 'e5', 'f4'): "King's Gambit",
    ('e4', 'e5', 'Nf3', 'd6'): "Philidor Defense",
    ('e4', 'e5', 'Bc4'): "Bishop's Opening",
    ('e4', 'e5', 'Ke2'): "Bongcloud Attack",    # 1. d4 açılışları
    ('d4', 'd5', 'c4'): "Queen's Gambit",
    ('d4', 'd5', 'c4', 'e6'): "Queen's Gambit Declined",
    ('d4', 'd5', 'c4', 'c6'): "Slav Defense",
    ('d4', 'd5', 'c4', 'dxc4'): "Queen's Gambit Accepted",    ('d4', 'Nf6'): "Indian Defenses",
    ('d4', 'Nf6', 'c4', 'g6'): "King's Indian Defense",
    ('d4', 'Nf6', 'c4', 'e6'): "Queen's Indian Defense",
    ('d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4'): "Nimzo-Indian Defense",
    ('d4', 'Nf6', 'c4', 'c5'): "Benoni Defense",
    ('d4', 'f5'): "Dutch Defense",
    ('d4', 'e6'): "French Defense Formation",
    ('d4', 'd5', 'Bf4'): "London System",
    ('d4', 'd5', 'Nf3'): "Queen's Pawn Game",
    ('d4', 'e5'): "Englund Gambit",
    ('d4', 'c5'): "Old Benoni",
    ('d4', 'g6'): "Modern Defense to Queen's Pawn",
    ('d4', 'c6'): "Caro-Kann Defense Formation",
    ('d4', 'b6'): "Queen's Indian Defense Formation",
    ('d4', 'f6'): "From's Gambit",    # 1. c4 openings
    ('c4',): "English Opening",
    ('c4', 'e5'): "English Opening: Reversed Sicilian",
    ('c4', 'c5'): "English Opening: Symmetrical Variation",
    ('c4', 'e6'): "English Opening: Agincourt Defense",
    ('c4', 'Nf6'): "English Opening: Indian Defense",
    ('c4', 'c6'): "English Opening: Caro-Kann Defense",
    ('c4', 'f5'): "English Opening: Dutch Defense",
    ('c4', 'b6'): "English Opening: Queen's Indian Defense",
    ('c4', 'g6'): "English Opening: King's Indian Defense",
    ('c4', 'e4'): "English Opening: Bremen System",

    # 1. Nf3 açılışları
    ('Nf3',): "Réti Opening",
    ('Nf3', 'd5'): "Réti: King's Indian Attack",
    ('Nf3', 'Nf6'): "Réti: Symmetrical Variation",
    ('Nf3', 'c5'): "Réti: Anti-Sicilian",
    ('Nf3', 'd5', 'c4'): "Réti: Advance Variation",
    ('Nf3', 'Nf6', 'c4'): "Réti: English Variation",
    ('Nf3', 'f5'): "Réti: Dutch Variation",
    ('Nf3', 'g6'): "Réti: King's Indian Setup",
    ('Nf3', 'c6'): "Réti: Slav Setup",
    ('Nf3', 'e6'): "Réti: Queen's Indian Setup",

    # Diğer açılışlar
    ('g3',): "King's Fianchetto Opening",
    ('b3',): "Larsen's Opening",
    ('f4',): "Bird's Opening",
    ('b4',): "Sokolsky Opening",
    ('a3',): "Anderssen's Opening",
    ('h3',): "Clemenz Opening",
    ('a4',): "Ware Opening",
    ('h4',): "Grob Attack",
    ('g4',): "Grob Opening",
    ('f3',): "Barnes Opening",

    # Modern sistemler
    ('c4', 'e5', 'Nc3', 'Nf6', 'g3'): "Botvinnik System",
    ('d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'Nf3'): "Neo-Grünfeld Defense",
    ('d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'g3'): "Queen's Indian: Fianchetto",
    ('e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4'): "Caro-Kann: Panov Attack",
    ('e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3'): "Sicilian: Najdorf",
    ('d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3'): "Slav Defense: Modern Line",
    ('e4', 'c5', 'Nc3', 'Nc6', 'g3', 'g6', 'Bg2'): "Closed Sicilian: Grand Prix Attack",
    ('d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4'): "King's Indian: Sämisch Variation",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O'): "Ruy Lopez: Closed",
    ('d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Be7'): "QGD: Classical Variation",

    # Hypermodern açılışlar
    ('g3', 'd5', 'Bg2'): "King's Indian Attack",
    ('Nf3', 'd5', 'g3'): "Reti: King's Indian Attack",
    ('c4', 'Nf6', 'g3'): "English: King's Indian Setup",
    ('g3', 'e5', 'Bg2'): "King's Indian Attack: Reversed Sicilian",
    ('Nf3', 'c5', 'c4'): "English: Four Knights System",

    # Gambit sistemleri
    ('e4', 'e5', 'f4', 'exf4'): "King's Gambit Accepted",
    ('d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'dxc4'): "Slav Gambit",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'b4'): "Evans Gambit",
    ('d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Nbd7'): "QGD: Cambridge Springs",
    ('e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4'): "Scotch Gambit",

    # Modern savunma sistemleri
    ('e4', 'g6', 'd4', 'Bg7'): "Modern Defense: Main Line",
    ('d4', 'g6', 'e4', 'Bg7'): "Modern Defense: Averbakh System",
    ('e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4'): "Caro-Kann: Classical",
    ('e4', 'e6', 'd4', 'd5', 'Nd2'): "French: Tarrasch",
    ('d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'a3'): "Queen's Indian: Petrosian System",

    # Deneysel açılışlar
    ('Na3',): "Sodium Attack",
    ('Nh3',): "Amar Opening",
    ('f3', 'e5', 'Kf2'): "Barnes Opening: Fool's Mate Defense",
    ('a4', 'e5'): "Ware Opening: Wing Attack",
    ('h4', 'd5'): "Grob Attack: Spike Attack",    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5'): "Italian Opening (Giuoco Piano)",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5'): "Ruy Lopez",
    ('e4', 'c5'): "Sicilian Defense",
    ('e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6'): "Sicilian Defense: Najdorf Variation",
    ('e4', 'e6'): "French Defense",
    ('e4', 'c6'): "Caro-Kann Defense",
    ('d4', 'd5', 'c4'): "Queen's Gambit",
    ('d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5'): "Queen's Gambit Declined",
    ('d4', 'd5', 'c4', 'dxc4'): "Queen's Gambit Accepted",
    ('d4', 'Nf6', 'c4', 'g6'): "King's Indian Defense",
    ('d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4'): "Nimzo-Indian Defense",
    ('d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6'): "Queen's Indian Defense",
    ('d4', 'Nf6', 'c4', 'c5'): "Benoni Defense",
    ('d4', 'f5'): "Dutch Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6'): "Two Knights Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'd4'): "Scotch Game",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'b4'): "Evans Gambit",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Be7'): "Hungarian Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'g3'): "King's Fianchetto Opening",
    ('e4', 'e5', 'Nf3', 'Nc6', 'c3'): "Ponziani Opening",
    ('d4', 'e5'): "Englund Gambit",
    ('e4', 'e5', 'f4'): "King's Gambit",
    ('e4', 'd5'): "Scandinavian Defense (Center Counter Defense)",    ('Nf3', 'd5', 'g3'): "King's Indian Attack",
    ('f4',): "Bird's Opening",
    ('b3',): "Larsen's Opening (Nimzo–Larsen Attack)",
    ('g3',): "King's Fianchetto Opening",
    ('Nc3', 'd5', 'e4'): "Blackmar–Diemer Gambit",
    ('e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6'): "Pirc Defense",
    ('d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5'): "Grünfeld Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7'): "Ruy Lopez: Closed",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Nxe4'): "Ruy Lopez: Open",
    ('e4', 'g6'): "Modern Defense",
    ('e4', 'b6'): "Owen's Defense",
    ('d4', 'b6'): "English Defense",    ('d4', 'd5', 'Bf4'): "London System",
    ('d4', 'Nf6', 'Nf3', 'g6', 'e3', 'Bg7', 'Be2', 'O-O', 'O-O', 'd6', 'c4'): "King's Indian Attack vs King's Indian Defense",
    ('e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'd6', 'Bg5'): "Sicilian Defense: Richter-Rauzer Attack",
    ('e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e5'): "Sicilian Defense: Sveshnikov Variation",
    ('e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e6'): "Sicilian Defense: Scheveningen Variation",
    ('e4', 'c5', 'Nf3', 'Nc6', 'Bb5'): "Sicilian Defense: Moscow Variation",
    ('e4', 'c5', 'Nf3', 'e6', 'd4', 'cxd4', 'Nxd4', 'a6'): "Sicilian Defense: Kan Variation",
    ('e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'g6'): "Sicilian Defense: Dragon Variation",
    ('e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e6'): "Sicilian Defense: Classical Variation",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5'): "Fried Liver Attack",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'd3'): "Two Knights Defense: Modern",
    ('e4', 'e5', 'Nc3'): "Vienna Game",
    ('e4', 'e5', 'Nc3', 'Nf6', 'f4'): "Vienna Gambit",
    ('e4', 'd6', 'd4', 'Nf6', 'Nc3', 'e5'): "Philidor Defense",
    ('e4', 'e5', 'Nf3', 'd6'): "Philidor Defense (Hanham Variation)",
    ('e4', 'e5', 'Qh5'): "Parham Attack",
    ('e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qa5'): "Scandinavian Defense: Main Line",
    ('e4', 'd5', 'exd5', 'Nf6'): "Scandinavian Defense: Modern Variation",
    ('d4', 'Nf6', 'c4', 'e6', 'Nf3', 'd5'): "Queen's Gambit Declined: Orthodox Defense",
    ('d4', 'Nf6', 'c4', 'e6', 'Nf3', 'd5', 'Nc3', 'Be7'): "Queen's Gambit Declined: Traditional",
    ('d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'e3', 'O-O', 'Bd3', 'd5'): "Nimzo-Indian: Classical",
    ('d4', 'd5', 'Nf3', 'Nf6', 'e3'): "Colle System",
    ('d4', 'Nf6', 'Nf3', 'd5', 'e3', 'e6', 'Bd3', 'Bd6', 'O-O', 'O-O'): "Colle-Zukertort System",
    ('d4', 'Nf6', 'c4', 'e6', 'g3'): "Catalan Opening",
    ('d4', 'd5', 'Nf3', 'Nf6', 'c4', 'e6', 'Nc3', 'Be7', 'Bg5'): "Queen's Gambit Declined: Lasker Defense",
    ('d4', 'd5', 'Nf3', 'Nf6', 'c4', 'c6'): "Slav Defense",
    ('d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'dxc4'): "Slav Defense: Main Line",
    ('d4', 'Nf6', 'c4', 'e6', 'Nc3', 'c5'): "Modern Benoni",
    ('e4', 'c5', 'Nf3', 'Nc6', 'Nc3'): "Closed Sicilian",
    ('e4', 'c5', 'Nc3'): "Sicilian: Closed Variation",
    ('e4', 'e5', 'Bc4'): "Bishop's Opening",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3'): "Italian Game: Giuoco Pianissimo",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3', 'Nf6', 'd4', 'exd4', 'cxd4', 'Bb4+'): "Italian Game: Légal Trap",
    ('e4', 'Nf6'): "Alekhine's Defense",
    ('e4', 'Nf6', 'e5', 'Nd5', 'd4', 'd6', 'Nf3', 'g6'): "Alekhine's Defense: Modern",
    ('d4', 'e6'): "Horwitz Defense",
    ('e4', 'h6'): "Clemenz Opening",
    ('e4', 'a6'): "St. George Defense",
    ('a4',): "Ware Opening",
    ('b4',): "Polish Opening (Orangutan)",
    ('g4',): "Grob Opening",
    ('Na3',): "Sodium Attack",
    ('Nc3', 'e5', 'd4'): "Van Geet Opening",
    ('d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O', 'Be2', 'e5', 'O-O', 'Nc6'): "King's Indian: Mar del Plata",
    ('e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be3', 'e6', 'f3', 'b5', 'Qd2', 'Nbd7', 'g4'): "Sicilian Najdorf: English Attack",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1', 'b5', 'Bb3', 'O-O'): "Ruy Lopez: Chigorin Defense",
    ('d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Be7', 'e3', 'h6', 'Bh4'): "Queen's Gambit: Cambridge Springs Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nf6', 'O-O', 'Nxe4'): "Ruy Lopez: Berlin Defense",
    ('d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'Qc2'): "Nimzo-Indian: Classical Variation",
    ('d4', 'd5', 'c4', 'c6', 'Nc3', 'Nf6', 'e3', 'e6', 'Nf3', 'Nbd7', 'Bd3'): "Semi-Slav Defense",
    ('e4', 'c5', 'b3'): "Sicilian Defense: Grand Prix Attack",
    ('d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Be2', 'O-O', 'Bg5'): "King's Indian: Averbakh Variation",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nd4'): "Ruy Lopez: Bird's Defense",
    ('d4', 'Nf6', 'Bg5'): "Trompowsky Attack",
    ('e4', 'c5', 'Nf3', 'e6', 'b3'): "Sicilian Defense: Closed Variation",
    ('d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'g3', 'Ba6'): "Queen's Indian: Fianchetto Variation",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'd3'): "Italian Game: Slow Italian",
    ('d4', 'f5', 'g3'): "Dutch Defense: Leningrad Variation",
    ('e4', 'c5', 'c3'): "Sicilian Defense: Alapin Variation",
    ('d4', 'd5', 'c4', 'e6', 'Nf3', 'Nf6', 'g3'): "Queen's Gambit: Catalan Variation",
    ('e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4'): "Caro-Kann: Classical Variation",
    ('d4', 'd5', 'c4', 'c6', 'Nf3', 'e6', 'e3'): "Slav Defense: Modern Variation",
    ('e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'g6'): "Sicilian: Accelerated Dragon",
    ('d4', 'Nf6', 'c4', 'c5', 'd5', 'b5'): "Benko Gambit",
    ('e4', 'e6', 'd4', 'd5', 'Nc3', 'Bb4'): "French Defense: Winawer Variation",
    ('e4', 'e6', 'd4', 'd5', 'e5'): "French Defense: Advance Variation",
    ('d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'dxc4', 'a4'): "Slav Defense: Modern Line",
    ('e4', 'c6', 'd4', 'd5', 'e5'): "Caro-Kann: Advance Variation",
    ('e4', 'c5', 'Nf3', 'd6', 'Bb5+'): "Sicilian Defense: Moscow Variation",
    ('d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'f3'): "Nimzo-Indian: Sämisch Variation",
    ('e4', 'e5', 'f4', 'exf4', 'Nf3'): "King's Gambit Accepted",
    ('d4', 'Nf6', 'c4', 'g6', 'f3'): "King's Indian: Sämisch Variation",
    ('e4', 'Nf6', 'e5', 'Nd5', 'c4'): "Alekhine Defense: Four Pawns Attack",
    ('d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'e3', 'Bf5'): "Slav Defense: Czech Variation",
    ('e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'd6'): "Petrov Defense: Classical Attack",
    ('d4', 'Nf6', 'c4', 'c5', 'd5', 'e6'): "Benoni Defense: Modern Variation",
    ('e4', 'e5', 'Bc4', 'Nf6', 'd3'): "Bishop's Opening: Berlin Defense"
}
