openings = {
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5'): "İtalyan Açılışı (Giuoco Piano)",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5'): "İspanyol Açılışı (Ruy Lopez)",
    ('e4', 'c5'): "Sicilian Defense",
    ('e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6'): "Sicilian Defense: Najdorf Variation",
    ('e4', 'e6'): "French Defense",
    ('e4', 'c6'): "Caro-Kann Defense",
    ('d4', 'd5', 'c4'): "Queen's Gambit",
    ('d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5'): "Queen's Gambit Declined",
    ('d4', 'd5', 'c4', 'dxc4'): "Queen's Gambit Accepted",
    ('d4', 'Nf6', 'c4', 'g6'): "King's Indian Defense",
    ('d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4'): "Nimzo-Indian Defense",
    ('d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6'): "Queen's Indian Defense",
    ('d4', 'Nf6', 'c4', 'c5'): "Benoni Defense",
    ('d4', 'f5'): "Dutch Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6'): "Two Knights Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'd4'): "Scotch Game",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'b4'): "Evans Gambit",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Be7'): "Hungarian Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'g3'): "King's Fianchetto Opening",
    ('e4', 'e5', 'Nf3', 'Nc6', 'c3'): "Ponziani Opening",
    ('d4', 'e5'): "Englund Gambit",
    ('e4', 'e5', 'f4'): "King's Gambit",
    ('e4', 'd5'): "Scandinavian Defense (Center Counter Defense)",
    ('Nf3', 'd5', 'g3'): "King's Indian Attack",
    ('c4',): "English Opening",
    ('f4',): "Bird's Opening",
    ('b3',): "Larsen's Opening (Nimzo–Larsen Attack)",
    ('g3',): "King's Fianchetto Opening",
    ('Nc3', 'd5', 'e4'): "Blackmar–Diemer Gambit",
    ('e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6'): "Pirc Defense",
    ('d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5'): "Grünfeld Defense",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7'): "Ruy Lopez: Closed",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Nxe4'): "Ruy Lopez: Open",
    ('e4', 'g6'): "Modern Defense",
    ('e4', 'b6'): "Owen's Defense",
    ('d4', 'b6'): "English Defense",
    ('c4', 'e5'): "English Opening: Reversed Sicilian",
    ('d4', 'd5', 'Bf4'): "London System",
    ('d4', 'Nf6', 'Nf3', 'g6', 'e3', 'Bg7', 'Be2', 'O-O', 'O-O', 'd6', 'c4'): "King's Indian Attack vs King's Indian Defense",
    ('e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'd6', 'Bg5'): "Sicilian Defense: Richter-Rauzer Attack",
    ('e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e5'): "Sicilian Defense: Sveshnikov Variation",
    ('e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e6'): "Sicilian Defense: Scheveningen Variation",
    ('e4', 'c5', 'Nf3', 'Nc6', 'Bb5'): "Sicilian Defense: Moscow Variation",
    ('e4', 'c5', 'Nf3', 'e6', 'd4', 'cxd4', 'Nxd4', 'a6'): "Sicilian Defense: Kan Variation",
    ('e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'g6'): "Sicilian Defense: Dragon Variation",
    ('e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e6'): "Sicilian Defense: Classical Variation",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5'): "Fried Liver Attack",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'd3'): "Two Knights Defense: Modern",
    ('e4', 'e5', 'Nc3'): "Vienna Game",
    ('e4', 'e5', 'Nc3', 'Nf6', 'f4'): "Vienna Gambit",
    ('e4', 'd6', 'd4', 'Nf6', 'Nc3', 'e5'): "Philidor Defense",
    ('e4', 'e5', 'Nf3', 'd6'): "Philidor Defense (Hanham Variation)",
    ('e4', 'e5', 'Qh5'): "Parham Attack",
    ('e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qa5'): "Scandinavian Defense: Main Line",
    ('e4', 'd5', 'exd5', 'Nf6'): "Scandinavian Defense: Modern Variation",
    ('d4', 'Nf6', 'c4', 'e6', 'Nf3', 'd5'): "Queen's Gambit Declined: Orthodox Defense",
    ('d4', 'Nf6', 'c4', 'e6', 'Nf3', 'd5', 'Nc3', 'Be7'): "Queen's Gambit Declined: Traditional",
    ('d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'e3', 'O-O', 'Bd3', 'd5'): "Nimzo-Indian: Classical",
    ('d4', 'd5', 'Nf3', 'Nf6', 'e3'): "Colle System",
    ('d4', 'Nf6', 'Nf3', 'd5', 'e3', 'e6', 'Bd3', 'Bd6', 'O-O', 'O-O'): "Colle-Zukertort System",
    ('d4', 'Nf6', 'c4', 'e6', 'g3'): "Catalan Opening",
    ('d4', 'd5', 'Nf3', 'Nf6', 'c4', 'e6', 'Nc3', 'Be7', 'Bg5'): "Queen's Gambit Declined: Lasker Defense",
    ('d4', 'd5', 'Nf3', 'Nf6', 'c4', 'c6'): "Slav Defense",
    ('d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'dxc4'): "Slav Defense: Main Line",
    ('d4', 'Nf6', 'c4', 'e6', 'Nc3', 'c5'): "Modern Benoni",
    ('e4', 'c5', 'Nf3', 'Nc6', 'Nc3'): "Closed Sicilian",
    ('e4', 'c5', 'Nc3'): "Sicilian: Closed Variation",
    ('e4', 'e5', 'Bc4'): "Bishop's Opening",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3'): "Italian Game: Giuoco Pianissimo",
    ('e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3', 'Nf6', 'd4', 'exd4', 'cxd4', 'Bb4+'): "Italian Game: Légal Trap",
    ('e4', 'Nf6'): "Alekhine's Defense",
    ('e4', 'Nf6', 'e5', 'Nd5', 'd4', 'd6', 'Nf3', 'g6'): "Alekhine's Defense: Modern",
    ('d4', 'e6'): "Horwitz Defense",
    ('e4', 'h6'): "Clemenz Opening",
    ('e4', 'a6'): "St. George Defense",
    ('a4',): "Ware Opening",
    ('b4',): "Polish Opening (Orangutan)",
    ('g4',): "Grob Opening",
    ('Na3',): "Sodium Attack",
    ('Nc3', 'e5', 'd4'): "Van Geet Opening",
    ('d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O', 'Be2', 'e5', 'O-O', 'Nc6'): "King's Indian: Mar del Plata",
    ('e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be3', 'e6', 'f3', 'b5', 'Qd2', 'Nbd7', 'g4'): "Sicilian Najdorf: English Attack",
}
